version: '3'

services:
  app:
    build: app
    expose: 
     - "8888" 

  balanceador:
    build: nginx
    ports:
     - "8888:8888"
    links:
     - app

  pruebas:
    build: jenkins
    volumes:
     - ./jenkins/data:/var/jenkins_home
    ports:
     - "8080:8080"
    
