version: '3'

services:
  app:
    build: app
    expose: 
     - "8888" 

  balanceador:
    build: nginx
    ports:
     - "8888:8888"
    links:
     - app

  pruebas:
    build: jenkins
    volumens:
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - "9000:8080"
    
